version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    reviewers:
      - "madstone-tech"
    assignees:
      - "madstone-tech"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
    # Group Go dependency updates to reduce PR noise
    groups:
      go-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "golang.org/x/vuln/cmd/govulncheck"
          - "github.com/golangci/golangci-lint"
    # Ignore specific dependencies that we want to manage manually
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "github.com/spf13/cobra"
        update-types: ["version-update:semver-major"]
      - dependency-name: "github.com/spf13/viper"
        update-types: ["version-update:semver-major"]
      - dependency-name: "google.golang.org/grpc"
        update-types: ["version-update:semver-major"]
      - dependency-name: "google.golang.org/protobuf"
        update-types: ["version-update:semver-major"]
      - dependency-name: "github.com/charmbracelet/bubbletea"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    reviewers:
      - "madstone-tech"
    assignees:
      - "madstone-tech"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    # Group GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - "*"

  # Docker (if we add Dockerfile in the future)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 2
    reviewers:
      - "madstone-tech"
    assignees:
      - "madstone-tech"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"