run:
  timeout: 5m
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  goimports:
    local-prefixes: github.com/madstone-tech/maestro

  govet:
    check-shadowing: true
    enable-all: true

  gocyclo:
    min-complexity: 10

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  gofumpt:
    extra-rules: true

  gosec:
    excludes:
      - G104 # Audit errors not checked - we handle this explicitly
    config:
      G306: "0644"

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

linters:
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - exhaustive  # too noisy for switches
    - gochecknoglobals  # we have some necessary globals
    - godot      # too strict for code comments
    - gomnd      # magic numbers are sometimes OK
    - wsl        # too opinionated about whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll

    # Exclude known false positives
    - text: "G404: Use of weak random number generator"
      linters:
        - gosec

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"

    # Exclude lll issues for long lines with URLs or similar
    - linters:
        - lll
      source: "^//.*http"

  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Show only new issues created after git revision
  new: false

  # Fix found issues (if supported by the linter)
  fix: false